# Generated by Django 4.1.3 on 2023-02-06 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en_us',
            field=models.CharField(help_text='название категории', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(help_text='название категории', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_en_us',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_en_us',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en_us',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='type_en_us',
            field=models.CharField(choices=[('PS', 'Статья'), ('NW', 'Новость')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='type_ru',
            field=models.CharField(choices=[('PS', 'Статья'), ('NW', 'Новость')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='название категории', max_length=255, unique=True),
        ),
    ]
